#!/bin/sh

# First check if dui tools are installed else use them under build/

which dui_root 2>/dev/null && dr=dui_root || dr=build/dui_root
which dui_wcom 2>/dev/null && com=dui_wcom || com=build/dui_wcom

$dr & rpid=$!

echo "Waiting for Root: $rpid"

until [ -e "/tmp/dui/$rpid" ]
do
	printf "waiting for session FIFO\r"
done
echo

echo "Building UI"

build/dui_wcom $rpid debugecho "Hallo Welt"
build/dui_wcom $rpid attach "root" "mainbox" vbox 1
build/dui_wcom $rpid attach "root/mainbox" "subboxtop" hbox 1
build/dui_wcom $rpid attach "root/mainbox" "subboxbottom" hbox 1
build/dui_wcom $rpid attach "root/mainbox/subboxtop" "HWLabel" label "Hallo Welt"
build/dui_wcom $rpid attach "root/mainbox/subboxtop" "BLabel" label "Bye"
build/dui_wcom $rpid attach "root/mainbox/subboxbottom" "CMButton" button "Click Me!"

wait $rpid
