#!/bin/sh

# First check if dui tools are installed else use them under build/

which dui_root 2>/dev/null && dr=dui_root || dr=build/dui_root
which dui_wcom 2>/dev/null && wcom=dui_wcom || wcom=build/dui_wcom

$dr & rpid=$!

echo $rpid

print_entry_text() {
	$wcom $rpid get "root/mainbox/entry" entry
	fb=$(cat "/tmp/dui/$rpid")
	$wcom $rpid set "root/mainbox/subboxtop/BLabel" label "$fb"
}

until [ -e "/tmp/dui/$rpid" ]
do
	printf "waiting for session FIFO\r"
done
echo

$wcom $rpid attach "root" "mainbox" vbox 0
$wcom $rpid attach "root/mainbox" "subboxtop" hbox 1
$wcom $rpid attach "root/mainbox" "subboxbottom" hbox 1
$wcom $rpid attach "root/mainbox/subboxtop" "HWLabel" label "Hallo Welt"
$wcom $rpid attach "root/mainbox/subboxtop" "BLabel" label "Bye"
$wcom $rpid attach "root/mainbox/subboxbottom" "CMButton" button "Click Me!"
$wcom $rpid attach "root/mainbox/subboxbottom" "CMButton2" button "Click Me!"
$wcom $rpid attach "root/mainbox" "entry" entry

action=$(cat "/tmp/dui/$rpid")

while [ "$action" != "quit" ]; do

	case "$action" in
		("CMButton clicked") print_entry_text;;
		(*) echo "Fallback";;
	esac
	
	action=$(cat "/tmp/dui/$rpid")
done 
